<?php

namespace customiesdevs\customies\item;

class ItemDataTypes {

// EnchantableSlot Component Slots
	public const SLOT_ALL = "all";
	public const SLOT_BOOTS = "armor_feet";
	public const SLOT_CHESTPLATE = "armor_torso";
	public const SLOT_HELMET = "armor_head";
	public const SLOT_LEGGINGS = "armor_legs";
	public const SLOT_AXE = "axe";
	public const SLOT_BOW = "bow";
	public const SLOT_COSMETIC_HEAD = "cosmetic_head";
	public const SLOT_CROSSBOW = "crossbow";
	public const SLOT_ELYTRA = "elytra";
	public const SLOT_FISHING_ROD = "fishing_rod";
	public const SLOT_FLINT = "flintsteel";
	public const SLOT_HOE = "hoe";
	public const SLOT_PICKAXE = "pickaxe";
	public const SLOT_SHEARS = "shears";
	public const SLOT_SHIELD = "shield";
	public const SLOT_SHOVEL = "shovel";
	public const SLOT_SWORD = "sword";
// EnchantableValue Component Values
	public const ARMOR_LEATHER = 15;
	public const ARMOR_CHAIN = 12;
	public const ARMOR_IRON = 9;
	public const ARMOR_GOLD = 25;
	public const ARMOR_DIAMOND = 10;
	public const ARMOR_TURTLE = 9;
	public const ARMOR_NETHERITE = 15;
	public const ARMOR_OTHER = 1;
	public const TOOL_WOOD = 15;
	public const TOOL_STONE = 5;
	public const TOOL_IRON = 14;
	public const TOOL_GOLD = 22;
	public const TOOL_DIAMOND = 10;
	public const TOOL_NETHERITE = 15;
	public const TOOL_OTHER = 1;
// Wearable Component Values
	public const SLOT_ARMOR_HEAD = "slot.armor.head"; // Helmet
	public const SLOT_ARMOR_CHEST = "slot.armor.chest"; // Chestplate
	public const SLOT_ARMOR_LEGS = "slot.armor.legs"; // Leggings
	public const SLOT_ARMOR_FEET = "slot.armor.feet"; // Boots
	public const SLOT_WEAPON_OFF_HAND = "slot.weapon.offhand"; // Offhand
	/** an extra armor slot for entities, like horses, limited to a single armor item but needing the effects of a full armor set */
	public const SLOT_EXTRA = "slot.armor.body";
// Animation Component Values
	public const ANIMATION_NONE = 0; // No Animation
	public const ANIMATION_EAT = 1; // Eat Animation
	public const ANIMATION_DRINK = 2; // Drink Animation
	public const ANIMATION_BLOCK = 3; // Block Animation
	public const ANIMATION_BOW = 4; // Bow Animation
	public const ANIMATION_CAMERA = 5; // Camera Animation
	public const ANIMATION_SPEAR = 6; // Spear/Trident Animation
	public const ANIMATION_CROSSBOW = 9; // Crossbow Animation
	public const ANIMATION_SPYGLASS = 10; // SpyGlass Animation
	public const ANIMATION_BRUSH = 12; // Brushing Animation
// DamageAbsorption Component Cause
	public const CAUSE_NONE = "none";
	public const CAUSE_ALL = "all";
	public const CAUSE_ANVIL = "anvil";
	public const CAUSE_BLOCK_EXPLOSION = "block_explosion";
	public const CAUSE_CAMPFIRE = "campfire";
	public const CAUSE_CHARGING = "charging";
	public const CAUSE_CONTACT = "contact";
	public const CAUSE_DROWNING = "drowning";
	public const CAUSE_ENTITY_ATTACK = "entity_attack";
	public const CAUSE_ENTITY_EXPLOSION = "entity_explosion";
	public const CAUSE_FALL = "fall";
	public const CAUSE_FALLING_BLOCK = "falling_block";
	public const CAUSE_FIRE = "fire";
	public const CAUSE_FIRE_TICK = "fire_tick";
	public const CAUSE_FIREWORKS = "fireworks";
	public const CAUSE_FLY_INTO_WALL = "fly_into_wall";
	public const CAUSE_FREEZING = "freezing";
	public const CAUSE_LAVA = "lava";
	public const CAUSE_LIGHTNING = "lightning";
	public const CAUSE_MAGIC = "magic";
	public const CAUSE_MAGMA = "magma";
	public const CAUSE_OVERRIDE = "override";
	public const CAUSE_PISTON = "piston";
	public const CAUSE_PROJECTILE = "projectile";
	public const CAUSE_RAM_ATTACK = "ram_attack";
	public const CAUSE_SELF_DESTRUCT = "self_destruct";
	public const CAUSE_SONIC_BOOM = "sonic_boom";
	public const CAUSE_SOUL_CAMPFIRE = "soul_campfire";
	public const CAUSE_STALACTITE = "stalactite";
	public const CAUSE_STALAGMITE = "stalagmite";
	public const CAUSE_STARVE = "starve";
	public const CAUSE_SUFFOCATION = "suffocation";
	public const CAUSE_TEMPERATURE = "temperature";
	public const CAUSE_THORNS = "thorns";
	public const CAUSE_VOID = "void";
	public const CAUSE_WITHER = "wither";
// DurabilitySensor Component Sounds
    public const SOUND_ITEM_USE_ON = "item.use.on";
    public const SOUND_HIT = "hit";
    public const SOUND_STEP = "step";
    public const SOUND_STEP_BABY = "step.baby";
    public const SOUND_FLY = "fly";
    public const SOUND_JUMP = "jump";
    public const SOUND_JUMP_PREVENT = "jump.prevent";
    public const SOUND_BREAK = "break";
    public const SOUND_PLACE = "place";
    public const SOUND_HEAVY_STEP = "heavy.step";
    public const SOUND_GALLOP = "gallop";
    public const SOUND_FALL = "fall";
    public const SOUND_HURT = "hurt";
    public const SOUND_HURT_BABY = "hurt.baby";
    public const SOUND_HURT_IN_WATER = "hurt.in.water";
    public const SOUND_DEATH = "death";
    public const SOUND_DEATH_BABY = "death.baby";
    public const SOUND_DEATH_IN_WATER = "death.in.water";
    public const SOUND_DEATH_TO_ZOMBIE = "death.to.zombie";
    public const SOUND_AMBIENT = "ambient";
    public const SOUND_AMBIENT_BABY = "ambient.baby";
    public const SOUND_AMBIENT_IN_WATER = "ambient.in.water";
    public const SOUND_AMBIENT_IN_AIR = "ambient.in.air";
    public const SOUND_AMBIENT_TAME = "ambient.tame";
    public const SOUND_AMBIENT_POLLINATE = "ambient.pollinate";
    public const SOUND_BREATHE = "breathe";
    public const SOUND_MAD = "mad";
    public const SOUND_BOOST = "boost";
    public const SOUND_BOW = "bow";
    public const SOUND_SQUISH_BIG = "squish.big";
    public const SOUND_SQUISH_SMALL = "squish.small";
    public const SOUND_FALL_BIG = "fall.big";
    public const SOUND_FALL_SMALL = "fall.small";
    public const SOUND_SPLASH = "splash";
    public const SOUND_FIZZ = "fizz";
    public const SOUND_FLAP = "flap";
    public const SOUND_SWIM = "swim";
    public const SOUND_DRINK = "drink";
    public const SOUND_DRINK_HONEY = "drink.honey";
    public const SOUND_DRINK_MILK = "drink.milk";
    public const SOUND_EAT = "eat";
    public const SOUND_TAKEOFF = "takeoff";
    public const SOUND_SHAKE = "shake";
    public const SOUND_PLOP = "plop";
    public const SOUND_LAND = "land";
    public const SOUND_SADDLE = "saddle";
    public const SOUND_ARMOR = "armor";
    public const SOUND_MOB_ARMOR_STAND_PLACE = "mob.armor_stand.place";
    public const SOUND_ADD_CHEST = "add.chest";
    public const SOUND_THROW = "throw";
    public const SOUND_ATTACK = "attack";
    public const SOUND_ATTACK_NO_DAMAGE = "attack.nodamage";
    public const SOUND_ATTACK_STRONG = "attack.strong";
    public const SOUND_WARN = "warn";
    public const SOUND_SHEAR = "shear";
    public const SOUND_MILK = "milk";
    public const SOUND_THUNDER = "thunder";
    public const SOUND_EXPLODE = "explode";
    public const SOUND_FIRE = "fire";
    public const SOUND_IGNITE = "ignite";
    public const SOUND_FUSE = "fuse";
    public const SOUND_STARE = "stare";
    public const SOUND_SPAWN = "spawn";
    public const SOUND_BORN = "born";
    public const SOUND_SHOOT = "shoot";
    public const SOUND_BREAK_BLOCK = "break.block";
    public const SOUND_LAUNCH = "launch";
    public const SOUND_BLAST = "blast";
    public const SOUND_LARGE_BLAST = "large.blast";
    public const SOUND_TWINKLE = "twinkle";
    public const SOUND_REMEDY = "remedy";
    public const SOUND_UNFECT = "unfect";
    public const SOUND_CONVERT_TO_DROWNED = "convert_to_drowned";
    public const SOUND_LEVELUP = "levelup";
    public const SOUND_BOW_HIT = "bow.hit";
    public const SOUND_BULLET_HIT = "bullet.hit";
    public const SOUND_EXTINGUISH_FIRE = "extinguish.fire";
    public const SOUND_ITEM_FIZZ = "item.fizz";
    public const SOUND_CHEST_OPEN = "chest.open";
    public const SOUND_CHEST_CLOSED = "chest.closed";
    public const SOUND_SHULKERBOX_OPEN = "shulkerbox.open";
    public const SOUND_SHULKERBOX_CLOSED = "shulkerbox.closed";
    public const SOUND_ENDERCHEST_OPEN = "enderchest.open";
    public const SOUND_ENDERCHEST_CLOSED = "enderchest.closed";
    public const SOUND_POWER_ON = "power.on";
    public const SOUND_POWER_OFF = "power.off";
    public const SOUND_ATTACH = "attach";
    public const SOUND_DETACH = "detach";
    public const SOUND_DENY = "deny";
    public const SOUND_TRIPOD = "tripod";
    public const SOUND_POP = "pop";
    public const SOUND_DROP_SLOT = "drop.slot";
    public const SOUND_NOTE = "note";
    public const SOUND_THORNS = "thorns";
    public const SOUND_PISTON_IN = "piston.in";
    public const SOUND_PISTON_OUT = "piston.out";
    public const SOUND_PORTAL = "portal";
    public const SOUND_WATER = "water";
    public const SOUND_LAVA_POP = "lava.pop";
    public const SOUND_LAVA = "lava";
    public const SOUND_BEACON_ACTIVATE = "beacon.activate";
    public const SOUND_BEACON_AMBIENT = "beacon.ambient";
    public const SOUND_BEACON_DEACTIVATE = "beacon.deactivate";
    public const SOUND_BEACON_POWER = "beacon.power";
// DurabilitySensor Component Particles
	public const PARTICLE_NONE = "none";
	public const PARTICLE_BUBBLE = "bubble";
	public const PARTICLE_BUBBLE_MANUAL = "bubblemanual";
	public const PARTICLE_CRIT = "crit";
	public const PARTICLE_BLOCK_FORCE_FIELD = "blockforcefield";
	public const PARTICLE_SMOKE = "smoke";
	public const PARTICLE_EXPLODE = "explode";
	public const PARTICLE_EVAPORATION = "evaporation";
	public const PARTICLE_FLAME = "flame";
	public const PARTICLE_CANDLE_FLAME = "candleflame";
	public const PARTICLE_LAVA = "lava";
	public const PARTICLE_LARGE_SMOKE = "largesmoke";
	public const PARTICLE_RED_DUST = "reddust";
	public const PARTICLE_RISING_BORDER_DUST = "risingborderdust";
	public const PARTICLE_ICON_CRACK = "iconcrack";
	public const PARTICLE_SNOWBALL_POOF = "snowballpoof";
	public const PARTICLE_LARGE_EXPLODE = "largeexplode";
	public const PARTICLE_HUGE_EXPLOSION = "hugeexplosion";
	public const PARTICLE_BREEZE_WIND_EXPLOSION = "breezewindexplosion";
	public const PARTICLE_MOB_FLAME = "mobflame";
	public const PARTICLE_HEART = "heart";
	public const PARTICLE_TERRAIN = "terrain";
	public const PARTICLE_TOWN_AURA = "townaura";
	public const PARTICLE_PORTAL = "portal";
	public const PARTICLE_WATER_SPLASH = "watersplash";
	public const PARTICLE_WATER_SPLASH_MANUAL = "watersplashmanual";
	public const PARTICLE_WATER_WAKE = "waterwake";
	public const PARTICLE_DRIP_WATER = "dripwater";
	public const PARTICLE_DRIP_LAVA = "driplava";
	public const PARTICLE_DRIP_HONEY = "driphoney";
	public const PARTICLE_STALACTITE_DRIP_WATER = "stalactitedripwater";
	public const PARTICLE_STALACTITE_DRIP_LAVA = "stalactitedriplava";
	public const PARTICLE_FALLING_DUST = "fallingdust";
	public const PARTICLE_MOB_SPELL = "mobspell";
	public const PARTICLE_MOB_SPELL_AMBIENT = "mobspellambient";
	public const PARTICLE_MOB_SPELL_INSTANTANEOUS = "mobspellinstantaneous";
	public const PARTICLE_INK = "ink";
	public const PARTICLE_SLIME = "slime";
	public const PARTICLE_RAIN_SPLASH = "rainsplash";
	public const PARTICLE_VILLAGER_ANGRY = "villagerangry";
	public const PARTICLE_VILLAGER_HAPPY = "villagerhappy";
	public const PARTICLE_ENCHANTING_TABLE = "enchantingtable";
	public const PARTICLE_TRACKING_EMITTER = "trackingemitter";
	public const PARTICLE_NOTE = "note";
	public const PARTICLE_WITCH_SPELL = "witchspell";
	public const PARTICLE_CARROT_BOOST = "carrotboost";
	public const PARTICLE_MOB_APPEARANCE = "mobappearance";
	public const PARTICLE_END_ROD = "endrod";
	public const PARTICLE_DRAGON_BREATH = "dragonbreath";
	public const PARTICLE_SPIT = "spit";
	public const PARTICLE_TOTEM = "totem";
	public const PARTICLE_FOOD = "food";
	public const PARTICLE_FIREWORKS_STARTER = "fireworksstarter";
	public const PARTICLE_FIREWORKS = "fireworks";
	public const PARTICLE_FIREWORKS_OVERLAY = "fireworksoverlay";
	public const PARTICLE_BALLOON_GAS = "balloongas";
	public const PARTICLE_COLORED_FLAME = "coloredflame";
	public const PARTICLE_SPARKLER = "sparkler";
	public const PARTICLE_CONDUIT = "conduit";
	public const PARTICLE_BUBBLE_COLUMN_UP = "bubblecolumnup";
	public const PARTICLE_BUBBLE_COLUMN_DOWN = "bubblecolumndown";
	public const PARTICLE_SNEEZE = "sneeze";
	public const PARTICLE_SHULKER_BULLET = "shulkerbullet";
	public const PARTICLE_BLEACH = "bleach";
	public const PARTICLE_DRAGON_DESTROY_BLOCK = "dragondestroyblock";
	public const PARTICLE_MYCELIUM_DUST = "myceliumdust";
	public const PARTICLE_FALLING_BORDER_DUST = "fallingborderdust";
	public const PARTICLE_CAMPFIRE_SMOKE = "campfiresmoke";
	public const PARTICLE_CAMPFIRE_SMOKE_TALL = "campfiresmoketall";
	public const PARTICLE_DRAGON_BREATH_FIRE = "dragonbreathfire";
	public const PARTICLE_DRAGON_BREATH_TRAIL = "dragonbreathtrail";
	public const PARTICLE_SOUL = "soul";
	public const PARTICLE_OBSIDIAN_TEAR = "obsidiantear";
	public const PARTICLE_PORTAL_REVERSE = "portalreverse";
	public const PARTICLE_SNOWFLAKE = "snowflake";
	public const PARTICLE_WAX = "wax";
	public const PARTICLE_ELECTRIC_SPARK = "electricspark";
	public const PARTICLE_SHRIEK = "shriek";
	public const PARTICLE_SCULK_SOUL = "sculksoul";
	public const PARTICLE_SONIC_EXPLOSION = "sonicexplosion";
	public const PARTICLE_DUST_PLUME = "dustplume";
	public const PARTICLE_WHITE_SMOKE = "whitesmoke";
	public const PARTICLE_VAULT_CONNECTION = "vaultconnection";
	public const PARTICLE_WIND_EXPLOSION = "windexplosion";
	public const PARTICLE_WOLF_ARMOR_CRACK = "wolfarmorcrack";
	public const PARTICLE_CREAKING_CRUMBLE = "creakingcrumble";
	public const PARTICLE_PALE_OAK_LEAVES = "paleoakleaves";
	public const PARTICLE_EYE_BLOSSOM_OPEN = "eyeblossomopen";
	public const PARTICLE_EYE_BLOSSOM_CLOSE = "eyeblossomclose";
// ItemTags Component / Tags Component Values
	# Tools
	public const TAG_IS_SWORD = "minecraft:is_sword";
	public const TAG_IS_TOOL = "minecraft:is_tool";
	public const TAG_IS_ARMOR = "minecraft:is_armor";
	public const TAG_IS_AXE = "minecraft:is_axe";
	public const TAG_IS_HOE = "minecraft:is_hoe";
	public const TAG_IS_PICKAXE = "minecraft:is_pickaxe";
	public const TAG_IS_SHOVEL = "minecraft:is_shovel";
	public const TAG_IS_TRIDENT = "minecraft:is_trident";
	# Pickaxe
	public const TAG_DIGGER = "minecraft:digger";
	# Food
	public const TAG_IS_COOKED = "minecraft:is_cooked";
	public const TAG_IS_MEAT = "minecraft:is_meat";
	public const TAG_IS_FOOD = "minecraft:is_food";
	public const TAG_IS_FISH = "minecraft:is_fish";
	# Tiers
	public const TAG_LEATHERTIER = "minecraft:leather_tier";
	public const TAG_WOOD_TIER = "minecraft:wooden_tier";
	public const TAG_STONE_TIER = "minecraft:stone_tier";
	public const TAG_GOLD_TIER = "minecraft:golden_tier";
	public const TAG_IRON_TIER = "minecraft:iron_tier";
	public const TAG_DIAMOND_TIER = "minecraft:diamond_tier";
	public const TAG_NETHERITE_TIER = "minecraft:netherite_tier";
	# Trims
	public const TAG_TRIM_MATERIALS = "minecraft:trim_materials";
	public const TAG_UPGRADE_TEMPLATE = "minecraft:transform_templates";
	public const TAG_TRIM_TEMPLATES = "minecraft:trim_templates";
	public const TAG_TRIMMABLE = "minecraft:trimmable_armors";
	# Other
	public const TAG_ARROW = "minecraft:arrow";
	public const TAG_BANNER = "minecraft:banner";
	public const TAG_BOAT = "minecraft:boat";
	public const TAG_LOGS = "minecraft:logs";
	public const TAG_DISC = "minecraft:music_disc";
	public const TAG_PLANKS = "minecraft:planks";
	public const TAG_SPAWNEGG = "minecraft:spawn_egg";
	public const TAG_DAMPERS = "minecraft:vibration_damper";
	public const TAG_WOOL = "minecraft:wool";
	public const TAG_FUEL = "minecraft:coals";


}